---
- name: OCP Block
  block:

  - name: Login to OpenShift
    redhat.openshift.openshift_auth:
      host: "{{ openshift_fqdn }}"
      username: "{{ openshift_user }}"
      password: "{{ openshift_password }}"
      validate_certs: false
    register: openshift_auth_results

  - name: Get Secret
    kubernetes.core.k8s_info:
      api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      host: "{{ openshift_fqdn }}"
      kind: Secret
      namespace: "{{ vm_name }}"
      validate_certs: false
    register: output

  - name: Set name of non approved host
    ansible.builtin.set_fact:
      crds: "{{ item.data['crds.yaml'] | b64decode }}"
      hostimport: "{{ item.data['import.yaml'] | b64decode }}"
    when: item.metadata.name == "{{ vm_name }}-import"
    loop: "{{ output.resources }}"
    loop_control:
      label: "{{ item.metadata.name }}"

  always:
    - name: If login succeeded, try to log out (revoke access token)
      redhat.openshift.openshift_auth:
        state: absent
        host: "{{ openshift_fqdn }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        validate_certs: false
      when: openshift_auth_results.openshift_auth.api_key is defined
