---
- name: OCP Block
  block:

  - name: Login to OpenShift
    redhat.openshift.openshift_auth:
      host: "{{ openshift_fqdn }}"
      username: "{{ openshift_user }}"
      password: "{{ openshift_password }}"
      validate_certs: false
    register: openshift_auth_results

  - name: Get Secret
    kubernetes.core.k8s_info:
      api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      host: "{{ openshift_fqdn }}"
      kind: Secret
      namespace: "{{ vm_name }}"
      validate_certs: false
    register: output

  - name: Set host import information
    ansible.builtin.set_fact:
      hostimport: "{{ item.data['import.yaml'] | b64decode }}"
    when: item.metadata.name == "{{ vm_name }}-import"
    loop: "{{ output.resources }}"
    loop_control:
      label: "{{ item.metadata.name }}"

  - name: Set kubeadminpassword
    ansible.builtin.set_fact:
      kubeadminpassword: "{{ item.data.password | b64decode }}"      
    when: item.metadata.name == "{{ vm_name }}-kubeadmin-password"
    loop: "{{ output.resources }}"
    loop_control:
      label: "{{ item.metadata.name }}"

  - name: Logout of main cluster
    redhat.openshift.openshift_auth:
      state: absent
      host: "{{ openshift_fqdn }}"
      api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
      validate_certs: false
    when: openshift_auth_results.openshift_auth.api_key is defined

  - name: Login to new cluster
    redhat.openshift.openshift_auth:
      host: "https://{{ apiip }}:6443"
      username: "kubeadmin"
      password: "{{ kubeadminpassword }}"
      validate_certs: false
    register: openshiftnew_auth_results

  - name: Import
    kubernetes.core.k8s:
      api_key: "{{ openshiftnew_auth_results.openshift_auth.api_key }}"
      host: "https://{{ apiip }}:6443"
      definition: "{{ hostimport }}"
      continue_on_error: true
      force: true
      validate_certs: false

  - name: If login succeeded, try to log out (revoke access token)
    redhat.openshift.openshift_auth:
      state: absent
      host: "https://{{ apiip }}:6443"
      api_key: "{{ openshiftnew_auth_results.openshift_auth.api_key }}"
      validate_certs: false
    when: openshiftnew_auth_results.openshift_auth.api_key is defined

  always:
    - name: If login succeeded, try to log out (revoke access token)
      redhat.openshift.openshift_auth:
        state: absent
        host: "{{ openshift_fqdn }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        validate_certs: false
      when: openshift_auth_results.openshift_auth.api_key is defined
